<?php

return [
    'standard_agricultural' => [
        'name' => 'Standard Agricultural Template',
        'description' => 'Comprehensive 63-account Chart of Accounts for agricultural research operations including Program and Non-Program accounts.',
        'accounts' => [
            // ─── PROGRAM — Revenue (4) ───────────────────────────────────
            [
                'code' => '4000',
                'name' => 'Revenue',
                'type' => 'REVENUE',
                'description' => 'Total revenue from all sources',
                'abbreviation' => 'REV',
                'parent' => null,
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Tracks all revenue streams for the organization',
                'tax_applicable' => false,
            ],
            [
                'code' => '4100',
                'name' => 'Harvest Revenue',
                'type' => 'REVENUE',
                'description' => 'Revenue generated from harvest activities',
                'abbreviation' => 'HARV-REV',
                'parent' => '4000',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Revenue from crop and product harvests',
                'tax_applicable' => false,
            ],
            [
                'code' => '4110',
                'name' => 'Crop Sales Revenue',
                'type' => 'REVENUE',
                'description' => 'Income from sale of harvested crops',
                'abbreviation' => 'CROP-REV',
                'parent' => '4100',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Sales proceeds from crop harvests',
                'tax_applicable' => false,
            ],
            [
                'code' => '4120',
                'name' => 'Product Testing Revenue',
                'type' => 'REVENUE',
                'description' => 'Revenue from product testing services',
                'abbreviation' => 'TEST-REV',
                'parent' => '4100',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Income earned from testing services provided',
                'tax_applicable' => false,
            ],

            // ─── PROGRAM — Expense (17) ─────────────────────────────────
            [
                'code' => '5000',
                'name' => 'Research Direct Costs',
                'type' => 'EXPENSE',
                'description' => 'Direct costs incurred in research activities',
                'abbreviation' => 'RES-DIR',
                'parent' => null,
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'All direct costs for research programs',
                'tax_applicable' => false,
            ],
            [
                'code' => '5100',
                'name' => 'Personnel Costs',
                'type' => 'EXPENSE',
                'description' => 'Salaries and wages for research personnel',
                'abbreviation' => 'PERS',
                'parent' => '5000',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Compensation for research staff',
                'tax_applicable' => false,
            ],
            [
                'code' => '5110',
                'name' => 'Researcher Salaries',
                'type' => 'EXPENSE',
                'description' => 'Monthly salaries for researchers',
                'abbreviation' => 'RES-SAL',
                'parent' => '5100',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Regular salary payments to researchers',
                'tax_applicable' => false,
            ],
            [
                'code' => '5120',
                'name' => 'Field Worker Wages',
                'type' => 'EXPENSE',
                'description' => 'Wages for field workers',
                'abbreviation' => 'FLD-WAG',
                'parent' => '5100',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Daily or weekly wages for field labor',
                'tax_applicable' => false,
            ],
            [
                'code' => '5130',
                'name' => 'Consultant Fees',
                'type' => 'EXPENSE',
                'description' => 'Fees paid to external consultants',
                'abbreviation' => 'CONSULT',
                'parent' => '5100',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Payments to specialized research consultants',
                'tax_applicable' => false,
            ],
            [
                'code' => '5200',
                'name' => 'Materials & Supplies',
                'type' => 'EXPENSE',
                'description' => 'Research materials and supplies',
                'abbreviation' => 'MAT-SUP',
                'parent' => '5000',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Consumable materials for research activities',
                'tax_applicable' => false,
            ],
            [
                'code' => '5210',
                'name' => 'Seeds & Planting Materials',
                'type' => 'EXPENSE',
                'description' => 'Seeds and materials for planting',
                'abbreviation' => 'SEED',
                'parent' => '5200',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Procurement of seeds for research plots',
                'tax_applicable' => false,
            ],
            [
                'code' => '5220',
                'name' => 'Fertilizers & Amendments',
                'type' => 'EXPENSE',
                'description' => 'Fertilizers and soil amendments',
                'abbreviation' => 'FERT',
                'parent' => '5200',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Application of fertilizers in research fields',
                'tax_applicable' => false,
            ],
            [
                'code' => '5230',
                'name' => 'Pesticides & Agrochemicals',
                'type' => 'EXPENSE',
                'description' => 'Pesticides and agrochemical products',
                'abbreviation' => 'PEST',
                'parent' => '5200',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Pest management chemicals for crops',
                'tax_applicable' => false,
            ],
            [
                'code' => '5240',
                'name' => 'Lab Chemicals & Reagents',
                'type' => 'EXPENSE',
                'description' => 'Laboratory chemicals and reagents',
                'abbreviation' => 'LAB-CHM',
                'parent' => '5200',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Chemicals used in laboratory testing',
                'tax_applicable' => false,
            ],
            [
                'code' => '5300',
                'name' => 'Equipment & Facilities',
                'type' => 'EXPENSE',
                'description' => 'Research equipment and facility costs',
                'abbreviation' => 'EQUIP',
                'parent' => '5000',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Equipment costs for research operations',
                'tax_applicable' => false,
            ],
            [
                'code' => '5310',
                'name' => 'Small Laboratory Equipment',
                'type' => 'EXPENSE',
                'description' => 'Small-scale laboratory equipment',
                'abbreviation' => 'LAB-EQP',
                'parent' => '5300',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Instruments and tools for lab work',
                'tax_applicable' => false,
            ],
            [
                'code' => '5320',
                'name' => 'Equipment Rental',
                'type' => 'EXPENSE',
                'description' => 'Rental fees for research equipment',
                'abbreviation' => 'EQP-RNT',
                'parent' => '5300',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Lease payments for borrowed equipment',
                'tax_applicable' => false,
            ],
            [
                'code' => '5330',
                'name' => 'Equipment Maintenance',
                'type' => 'EXPENSE',
                'description' => 'Maintenance and repair of equipment',
                'abbreviation' => 'EQP-MNT',
                'parent' => '5300',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Routine and emergency equipment repairs',
                'tax_applicable' => false,
            ],
            [
                'code' => '5400',
                'name' => 'Travel & Transportation',
                'type' => 'EXPENSE',
                'description' => 'Travel and transportation costs',
                'abbreviation' => 'TRVL',
                'parent' => '5000',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Costs for research-related travel',
                'tax_applicable' => false,
            ],
            [
                'code' => '5410',
                'name' => 'Domestic Travel',
                'type' => 'EXPENSE',
                'description' => 'Domestic travel expenses',
                'abbreviation' => 'DOM-TRV',
                'parent' => '5400',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Transportation within the country',
                'tax_applicable' => false,
            ],
            [
                'code' => '5420',
                'name' => 'Accommodation & Lodging',
                'type' => 'EXPENSE',
                'description' => 'Hotel and lodging expenses',
                'abbreviation' => 'ACCOM',
                'parent' => '5400',
                'category' => 'PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Overnight stays during field work or travel',
                'tax_applicable' => false,
            ],

            // ─── NON-PROGRAM — Revenue (5) ──────────────────────────────
            [
                'code' => '4200',
                'name' => 'Non-Program Revenue',
                'type' => 'REVENUE',
                'description' => 'Revenue not tied to specific programs',
                'abbreviation' => 'NP-REV',
                'parent' => '4000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Operational revenue streams',
                'tax_applicable' => false,
            ],
            [
                'code' => '4210',
                'name' => 'Grant Income',
                'type' => 'REVENUE',
                'description' => 'Income from grants received',
                'abbreviation' => 'GRANT',
                'parent' => '4200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Government or foundation grants',
                'tax_applicable' => false,
            ],
            [
                'code' => '4220',
                'name' => 'Donor Funding',
                'type' => 'REVENUE',
                'description' => 'Funding received from donors',
                'abbreviation' => 'DONOR',
                'parent' => '4200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Donations and philanthropic contributions',
                'tax_applicable' => false,
            ],
            [
                'code' => '4230',
                'name' => 'Other Income',
                'type' => 'REVENUE',
                'description' => 'Miscellaneous income sources',
                'abbreviation' => 'OTH-INC',
                'parent' => '4200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Income not classified elsewhere',
                'tax_applicable' => false,
            ],
            [
                'code' => '4240',
                'name' => 'Internal Service Income',
                'type' => 'REVENUE',
                'description' => 'Income from internal services',
                'abbreviation' => 'INT-SVC',
                'parent' => '4200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Revenue from services provided to other departments',
                'tax_applicable' => false,
            ],

            // ─── NON-PROGRAM — Research Support (5) ─────────────────────
            [
                'code' => '5500',
                'name' => 'Research Support Costs',
                'type' => 'EXPENSE',
                'description' => 'Indirect support costs for research',
                'abbreviation' => 'RES-SUP',
                'parent' => '5000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Support costs that enable research activities',
                'tax_applicable' => false,
            ],
            [
                'code' => '5510',
                'name' => 'Data Analysis & Statistics',
                'type' => 'EXPENSE',
                'description' => 'Data analysis and statistical services',
                'abbreviation' => 'DATA-AN',
                'parent' => '5500',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Statistical analysis of research data',
                'tax_applicable' => false,
            ],
            [
                'code' => '5520',
                'name' => 'Publication & Dissemination',
                'type' => 'EXPENSE',
                'description' => 'Costs for publishing and disseminating research',
                'abbreviation' => 'PUB',
                'parent' => '5500',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Knowledge',
                'typical_usage' => 'Journal articles and conference publications',
                'tax_applicable' => false,
            ],
            [
                'code' => '5530',
                'name' => 'Research Indirect Costs',
                'type' => 'EXPENSE',
                'description' => 'Indirect costs allocated to research',
                'abbreviation' => 'RES-IND',
                'parent' => '5500',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'Overhead costs charged to research programs',
                'tax_applicable' => false,
            ],
            [
                'code' => '5540',
                'name' => 'Overhead Allocation',
                'type' => 'EXPENSE',
                'description' => 'Allocated overhead costs',
                'abbreviation' => 'OVRHD',
                'parent' => '5500',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Research',
                'typical_usage' => 'General overhead distributed to departments',
                'tax_applicable' => false,
            ],

            // ─── NON-PROGRAM — Administrative (16) ──────────────────────
            [
                'code' => '6000',
                'name' => 'Administrative Expenses',
                'type' => 'EXPENSE',
                'description' => 'General administrative operating costs',
                'abbreviation' => 'ADMIN',
                'parent' => null,
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Day-to-day administrative operations',
                'tax_applicable' => false,
            ],
            [
                'code' => '6100',
                'name' => 'Admin Personnel',
                'type' => 'EXPENSE',
                'description' => 'Salaries for administrative staff',
                'abbreviation' => 'ADM-PRS',
                'parent' => '6000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Administrative staff compensation',
                'tax_applicable' => false,
            ],
            [
                'code' => '6110',
                'name' => 'Finance Staff Salaries',
                'type' => 'EXPENSE',
                'description' => 'Salaries for finance department staff',
                'abbreviation' => 'FIN-SAL',
                'parent' => '6100',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Accounting and finance team payroll',
                'tax_applicable' => false,
            ],
            [
                'code' => '6120',
                'name' => 'HR & Support Staff',
                'type' => 'EXPENSE',
                'description' => 'Salaries for HR and support personnel',
                'abbreviation' => 'HR-STF',
                'parent' => '6100',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Human resources and support team payroll',
                'tax_applicable' => false,
            ],
            [
                'code' => '6200',
                'name' => 'Office Operations',
                'type' => 'EXPENSE',
                'description' => 'Daily office operating expenses',
                'abbreviation' => 'OFF-OPS',
                'parent' => '6000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Routine office operational costs',
                'tax_applicable' => false,
            ],
            [
                'code' => '6210',
                'name' => 'Office Supplies',
                'type' => 'EXPENSE',
                'description' => 'Stationery and office supplies',
                'abbreviation' => 'OFF-SUP',
                'parent' => '6200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Paper, pens, and consumable office items',
                'tax_applicable' => false,
            ],
            [
                'code' => '6220',
                'name' => 'Office Equipment',
                'type' => 'EXPENSE',
                'description' => 'Office equipment purchases',
                'abbreviation' => 'OFF-EQP',
                'parent' => '6200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Computers, furniture, and office hardware',
                'tax_applicable' => false,
            ],
            [
                'code' => '6230',
                'name' => 'Telecommunications',
                'type' => 'EXPENSE',
                'description' => 'Phone and telecom service costs',
                'abbreviation' => 'TELECOM',
                'parent' => '6200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Phone lines and communication services',
                'tax_applicable' => false,
            ],
            [
                'code' => '6240',
                'name' => 'Electricity & Utilities',
                'type' => 'EXPENSE',
                'description' => 'Electricity and utility bills',
                'abbreviation' => 'UTIL',
                'parent' => '6200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Monthly electricity and water bills',
                'tax_applicable' => false,
            ],
            [
                'code' => '6250',
                'name' => 'Internet & Software',
                'type' => 'EXPENSE',
                'description' => 'Internet and software subscriptions',
                'abbreviation' => 'INT-SFT',
                'parent' => '6200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Cloud services and software licenses',
                'tax_applicable' => false,
            ],
            [
                'code' => '6300',
                'name' => 'Professional Services',
                'type' => 'EXPENSE',
                'description' => 'External professional service fees',
                'abbreviation' => 'PROF-SV',
                'parent' => '6000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Outsourced professional services',
                'tax_applicable' => false,
            ],
            [
                'code' => '6310',
                'name' => 'Legal & Compliance',
                'type' => 'EXPENSE',
                'description' => 'Legal and compliance costs',
                'abbreviation' => 'LEGAL',
                'parent' => '6300',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Legal counsel and regulatory compliance',
                'tax_applicable' => false,
            ],
            [
                'code' => '6320',
                'name' => 'External Audit Fees',
                'type' => 'EXPENSE',
                'description' => 'Fees for external auditing services',
                'abbreviation' => 'AUDIT',
                'parent' => '6300',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Annual and periodic audit fees',
                'tax_applicable' => false,
            ],
            [
                'code' => '6330',
                'name' => 'Consulting Services',
                'type' => 'EXPENSE',
                'description' => 'External consulting fees',
                'abbreviation' => 'CONSLT',
                'parent' => '6300',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Management and operational consultants',
                'tax_applicable' => false,
            ],
            [
                'code' => '6400',
                'name' => 'Marketing & Communication',
                'type' => 'EXPENSE',
                'description' => 'Marketing and communication costs',
                'abbreviation' => 'MKT',
                'parent' => '6000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Branding and outreach activities',
                'tax_applicable' => false,
            ],
            [
                'code' => '6410',
                'name' => 'Training & Events',
                'type' => 'EXPENSE',
                'description' => 'Training programs and event costs',
                'abbreviation' => 'TRAIN',
                'parent' => '6400',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Staff training and organizational events',
                'tax_applicable' => false,
            ],

            // ─── NON-PROGRAM — General & Administrative (5) ────────────
            [
                'code' => '6500',
                'name' => 'General & Administrative',
                'type' => 'EXPENSE',
                'description' => 'General administrative costs',
                'abbreviation' => 'GEN-ADM',
                'parent' => '6000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Miscellaneous administrative expenses',
                'tax_applicable' => false,
            ],
            [
                'code' => '6510',
                'name' => 'Insurance',
                'type' => 'EXPENSE',
                'description' => 'Insurance premiums',
                'abbreviation' => 'INSUR',
                'parent' => '6500',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Property, liability, and health insurance',
                'tax_applicable' => false,
            ],
            [
                'code' => '6520',
                'name' => 'Bank Charges',
                'type' => 'EXPENSE',
                'description' => 'Banking fees and charges',
                'abbreviation' => 'BANK',
                'parent' => '6500',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Financial',
                'typical_usage' => 'Transaction fees and bank service charges',
                'tax_applicable' => false,
            ],
            [
                'code' => '6530',
                'name' => 'Membership & Dues',
                'type' => 'EXPENSE',
                'description' => 'Membership fees and dues',
                'abbreviation' => 'MEMBR',
                'parent' => '6500',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Professional and industry association fees',
                'tax_applicable' => false,
            ],
            [
                'code' => '6540',
                'name' => 'Miscellaneous Expenses',
                'type' => 'EXPENSE',
                'description' => 'Other uncategorized expenses',
                'abbreviation' => 'MISC',
                'parent' => '6500',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Administrative',
                'typical_usage' => 'Expenses not fitting other categories',
                'tax_applicable' => false,
            ],

            // ─── NON-PROGRAM — Financial (5) ────────────────────────────
            [
                'code' => '7000',
                'name' => 'Financial Expenses',
                'type' => 'EXPENSE',
                'description' => 'Financial and banking related expenses',
                'abbreviation' => 'FIN-EXP',
                'parent' => null,
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Financial',
                'typical_usage' => 'Costs related to financial operations',
                'tax_applicable' => false,
            ],
            [
                'code' => '7100',
                'name' => 'Interest Expense',
                'type' => 'EXPENSE',
                'description' => 'Interest paid on loans and borrowings',
                'abbreviation' => 'INTREST',
                'parent' => '7000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Financial',
                'typical_usage' => 'Interest charges on outstanding debt',
                'tax_applicable' => false,
            ],
            [
                'code' => '7110',
                'name' => 'Loan Interest',
                'type' => 'EXPENSE',
                'description' => 'Interest on institutional loans',
                'abbreviation' => 'LOAN-INT',
                'parent' => '7100',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Financial',
                'typical_usage' => 'Monthly interest on bank loans',
                'tax_applicable' => false,
            ],
            [
                'code' => '7200',
                'name' => 'Foreign Exchange',
                'type' => 'EXPENSE',
                'description' => 'Foreign exchange costs',
                'abbreviation' => 'FX',
                'parent' => '7000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Financial',
                'typical_usage' => 'Currency conversion fees and losses',
                'tax_applicable' => false,
            ],
            [
                'code' => '7210',
                'name' => 'FX Loss',
                'type' => 'EXPENSE',
                'description' => 'Realized foreign exchange losses',
                'abbreviation' => 'FX-LOSS',
                'parent' => '7200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Financial',
                'typical_usage' => 'Losses from unfavorable currency movements',
                'tax_applicable' => false,
            ],

            // ─── NON-PROGRAM — Non-Operating (6) ────────────────────────
            [
                'code' => '8000',
                'name' => 'Non-Operating Expenses',
                'type' => 'EXPENSE',
                'description' => 'Expenses outside normal operations',
                'abbreviation' => 'NON-OP',
                'parent' => null,
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Costs not part of regular operations',
                'tax_applicable' => false,
            ],
            [
                'code' => '8100',
                'name' => 'Asset Disposal Losses',
                'type' => 'EXPENSE',
                'description' => 'Losses from disposing of assets',
                'abbreviation' => 'DISPOS',
                'parent' => '8000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Write-off when assets sold below book value',
                'tax_applicable' => false,
            ],
            [
                'code' => '8110',
                'name' => 'Equipment Disposal',
                'type' => 'EXPENSE',
                'description' => 'Loss on disposal of equipment',
                'abbreviation' => 'EQP-DIS',
                'parent' => '8100',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Disposal costs for retired equipment',
                'tax_applicable' => false,
            ],
            [
                'code' => '8200',
                'name' => 'Write-offs & Provisions',
                'type' => 'EXPENSE',
                'description' => 'Write-offs and provision expenses',
                'abbreviation' => 'WRITE',
                'parent' => '8000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Recording of impaired assets or debts',
                'tax_applicable' => false,
            ],
            [
                'code' => '8210',
                'name' => 'Bad Debt Provision',
                'type' => 'EXPENSE',
                'description' => 'Provision for uncollectable debts',
                'abbreviation' => 'BAD-DT',
                'parent' => '8200',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Reserves for accounts receivable unlikely to be collected',
                'tax_applicable' => false,
            ],
            [
                'code' => '8300',
                'name' => 'Penalties & Fines',
                'type' => 'EXPENSE',
                'description' => 'Penalties and fine charges',
                'abbreviation' => 'PENALTY',
                'parent' => '8000',
                'category' => 'NON_PROGRAM',
                'sub_category' => 'Operational',
                'typical_usage' => 'Regulatory penalties and late payment fines',
                'tax_applicable' => false,
            ],
        ],
    ],
];
